### ISSUE TITLE
请教一个与项目无关的问题

### ISSUE THREAD

**Issue by W4J1e** [liujiayu5566/MockGps#2]
开发者你好。
我现在用的 MIUI 14，此前我试用了 lsposed 框架里的 Fuck location， 但是闪退。找了好大一圈，找到了 MockGps，刚才试了一下，因为微信内应用定位用的是腾讯地图的 sdk ，所以不生效。
现在好像都没找到更高可用性的虚拟定位模块或软件，请问是因为难度更大了还是人们对这个功能的需求普遍没以前那么强了呀？

**Comment by liujiayu5566** [comment]
软件的原理就是通过系统LocationManager自带api实现，定位程序都能检测出来是mock的数据。腾讯地图有反mock的机制，默认是开启的，所以无法直接影响定位结果。之前测试过，断网进入腾讯地图后，再开始网络进行mock的话定位是可以生效的，但是也只能持续一段时间，微信的话不知道是否也是这样的。
这个需求我感觉蛮大的，但是要想真正修改定位数据，只能通过root的方式吧。这个软件的话主要用于开发使用，尤其是导航相关的开发，可以减少自测开发成本。

**Comment by W4J1e** [comment]
感谢回复。
我root了，也尝试过其它的软件或者模块，有个软件应该是可以的，但是检测我没有root，不知道是不是root隐藏导致的。
其实我目前的需求也不高，就是想看看那个加油站每天的优惠是不是不同，要在800米以内才能试着付款看实际金额。
好怀念好多年以前通过模块修改定位的日子啊。

**Comment by liujiayu5566** [comment]
如果想root的话可以使用Magisk来实现。我这个软件root的话应用也没法满足你得需求，我这个都是使用google开放的api来实现模拟定位，主要用于开发测试。地图类软件都会检测到定位来源（真实定位or模拟定位）。root的话用什么软件能满足你得需求，这个我也不知哈。

**Comment by W4J1e** [comment]
@P3R5T7U9 那个软件我已记不得叫什么了，使用root是付费功能，我没测试到实际能否成功。
然后，我也发现为什么它总是提示我没有root，因为我安装了shamiko模块，它检测不到Magisk存在。
再然后，issue的逻辑是，你参与了评论就会自动关注这个话题，然后话题里无论有没有与你相关的评论都会发邮件提醒，所以导致惊动了开发者大佬。
最后，想请问一下那个v站，是v2ex 吗？
