### ISSUE TITLE
一点小介意跟一点小bug

### ISSUE THREAD

**Issue by miao1986** [liujiayu5566/MockGps#20]
1，软件没暗色模式，在暗色模式是看不到设置里的字体的一片全黑。当然这不影响任何使用。
2，软件更新后才出现的问题，当模拟行驶后，点暂停（实际上是停止，会回到原来真实地址）上面是本来就这样设置的，就是顺嘴说下，行驶路线行驶一段距离后点暂停，小地图上还会显示导航的路线。这个原来应该是不会显示路线了的。不知道是不是我记错了哦。当然这也是不影响任何使用的。
3，这个是个小介意，就是感觉定位震动后，震动频率1秒一次是不是太快了。最好也能跟震动范围一样设置个范围值。

**Comment by liujiayu5566** [comment]
好，收到建议。我已经改好了，但是没自测，等这段时间忙完的，我还会更新一版本。
